apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: auth
  template:
    metadata:
      labels:
        app: auth
        tier: auth
    spec:
      containers:
        - name: auth-app
          image: sr2020/eva-auth:latest
          volumeMounts:
            - name: auth-env
              mountPath: /var/www/html/.env
              subPath: .env
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: auth-configmap
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
      volumes:
        - name: auth-env
          secret:
            secretName: auth-env
            items:
              - key: .env
                path: .env
